CREATE TABLE MOVIE(
MVNO NUMBER , -- 영화 번호
MVNAME VARCHAR2 NOT NULL, -- 영화 이름
MVDIRECTOR VARCHAR2 NOT NULL, --영화 감독
MVCLASS VARCHAR2 NOT NULL,--영화등급
MVBOOKINGRATE NUMBER, --영화 예매률 / 계산 필요
MVBOOKRANK NUMBER, --영화 예매 순위 / 계산 필요
MVONSCREEN BOOLEAN NOT NULL,--영화 상영 여부
MVRUNTIME NUMBER, --영화 시간
FOREIGN KEY(GENRENO) REFERENCES GENRE(GENRONO),
PRIMARY KEY(MVNO)
);

CREATE TABLE SCREENWAY(
SCRNO NUMBER,
SCRWAY VARCHAR2
);

CREATE TABLE SCREEN (
SCRNO NUMBER, --상영 번호
ZONE VARCHAR2, --지역
SCRDATE DATE, --상영날짜
CINEMA VARCHAR2, --영화관
THEATER VARCHAR2, --상영관
FOREIGN KEY(SCRWAY) REFERENCES SCREENWAY(SCRNO),
PRIMARY KEY(SCRNO)
);

CREATE TABLE CINEMA (

);


CREATE TABLE THEATER (

SCRSTART NUMBER, --상영시작시간 
SCREND NUMBER, --상영종료시간

);

CREATE TABLE SEAT (
TICKETNO NUMBER, --티켓 일련번호
SEATCNT NUMBER, --좌석 개수
KIND VARCHAR2, --관람인 종류
SEATNUM NUMBER, --좌석 번호(좌석 배치 고려 X)
PRIMARY KEY(TICKETNO),
FOREIGN KEY(SCRNO) REFERENCES SCREEN(SCRNO)
);

CREATE TABLE PAY(
PAYNO NUMBER, --결제 번호
PAYWAY VARCHAR2, --결제방식
PRICE NUMBER, --결제 가격
FOREIGN KEY(POINT) REFERENCES USER(POINT),
FOREIGN KEY(USERID) REFERENCES USER(USERID),
PRIMARY KEY(PAYNO)
);

CREATE TABLE GENRE(
GENRENO NUMBER,
GENRENAME VARCHAR2
);

CREATE TABLE USER(
USERID VARCHAR2,--아이디
USERNAME VARCHAR2,--이름
USERPW VARCHAR2,--비밀번호
USEREMAIL VARCHAR2,--이메일
USERBITRH DATE,--생년월일
USERPHONE NUMBER, --전화번호
POINT NUMBER, --포인트
FOREIGN KEY(FAVORGENRE) REFERENCES GENRE(GENRONO),
FOREIGN KEY(TICKETNO) REFERENCES SEAT(TICKETNO)
);

CREATE TABLE POINT(

);