<<<<<<< HEAD
<<<<<<< HEAD
CREATE TABLE MOVIE(
MVNO NUMBER , -- ¿µÈ­ ¹øÈ£
MVNAME VARCHAR2 NOT NULL, -- ¿µÈ­ ÀÌ¸§
MVDIRECTOR VARCHAR2 NOT NULL, --¿µÈ­ °¨µ¶
MVCLASS VARCHAR2 NOT NULL,--¿µÈ­µî±Þ
MVBOOKINGRATE NUMBER, --¿µÈ­ ¿¹¸Å·ü / °è»ê ÇÊ¿ä
MVBOOKRANK NUMBER, --¿µÈ­ ¿¹¸Å ¼øÀ§ / °è»ê ÇÊ¿ä
MVONSCREEN BOOLEAN NOT NULL,--¿µÈ­ »ó¿µ ¿©ºÎ
MVRUNTIME NUMBER, --¿µÈ­ ½Ã°£
=======
CREATE TABLE MOVIE(
MVNO NUMBER , -- ï¿½ï¿½È­ ï¿½ï¿½È£
MVNAME VARCHAR2 NOT NULL, -- ï¿½ï¿½È­ ï¿½Ì¸ï¿½
MVDIRECTOR VARCHAR2 NOT NULL, --ï¿½ï¿½È­ ï¿½ï¿½ï¿½ï¿½
MVCLASS VARCHAR2 NOT NULL,--ï¿½ï¿½È­ï¿½ï¿½ï¿½
MVBOOKINGRATE NUMBER, --ï¿½ï¿½È­ ï¿½ï¿½ï¿½Å·ï¿½ / ï¿½ï¿½ï¿½ ï¿½Ê¿ï¿½
MVBOOKRANK NUMBER, --ï¿½ï¿½È­ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ / ï¿½ï¿½ï¿½ ï¿½Ê¿ï¿½
MVONSCREEN BOOLEAN NOT NULL,--ï¿½ï¿½È­ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
MVRUNTIME NUMBER, --ï¿½ï¿½È­ ï¿½Ã°ï¿½
>>>>>>> d44d9151d7cd44fcf351008a550749065f5d2c5d
FOREIGN KEY(GENRENO) REFERENCES GENRE(GENRONO),
PRIMARY KEY(MVNO)
);

CREATE TABLE SCREENWAY(
SCRNO NUMBER,
SCRWAY VARCHAR2
);

CREATE TABLE SCREEN (
<<<<<<< HEAD
SCRNO NUMBER, --»ó¿µ ¹øÈ£
ZONE VARCHAR2, --Áö¿ª
SCRDATE DATE, --»ó¿µ³¯Â¥
CINEMA VARCHAR2, --¿µÈ­°ü
THEATER VARCHAR2, --»ó¿µ°ü
=======
SCRNO NUMBER, --ï¿½ï¿½ ï¿½ï¿½È£
ZONE VARCHAR2, --ï¿½ï¿½ï¿½ï¿½
SCRDATE DATE, --ï¿½ó¿µ³ï¿½Â¥
CINEMA VARCHAR2, --ï¿½ï¿½È­ï¿½ï¿½
THEATER VARCHAR2, --ï¿½ó¿µ°ï¿½
>>>>>>> d44d9151d7cd44fcf351008a550749065f5d2c5d
FOREIGN KEY(SCRWAY) REFERENCES SCREENWAY(SCRNO),
PRIMARY KEY(SCRNO)
);

CREATE TABLE CINEMA (

);


CREATE TABLE THEATER (

<<<<<<< HEAD
SCRSTART NUMBER, --»ó¿µ½ÃÀÛ½Ã°£ 
SCREND NUMBER, --»ó¿µÁ¾·á½Ã°£
=======
SCRSTART NUMBER, --ï¿½ó¿µ½ï¿½ï¿½Û½Ã°ï¿½ 
SCREND NUMBER, --ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ã°ï¿½
>>>>>>> d44d9151d7cd44fcf351008a550749065f5d2c5d

);

CREATE TABLE SEAT (
<<<<<<< HEAD
TICKETNO NUMBER, --Æ¼ÄÏ ÀÏ·Ã¹øÈ£
SEATCNT NUMBER, --ÁÂ¼® °³¼ö
KIND VARCHAR2, --°ü¶÷ÀÎ Á¾·ù
SEATNUM NUMBER, --ÁÂ¼® ¹øÈ£(ÁÂ¼® ¹èÄ¡ °í·Á X)
=======
TICKETNO NUMBER, --Æ¼ï¿½ï¿½ ï¿½Ï·Ã¹ï¿½È£
SEATCNT NUMBER, --ï¿½Â¼ï¿½ ï¿½ï¿½ï¿½ï¿½
KIND VARCHAR2, --ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
SEATNUM NUMBER, --ï¿½Â¼ï¿½ ï¿½ï¿½È£(ï¿½Â¼ï¿½ ï¿½ï¿½Ä¡ ï¿½ï¿½ï¿½ï¿½ X)
>>>>>>> d44d9151d7cd44fcf351008a550749065f5d2c5d
PRIMARY KEY(TICKETNO),
FOREIGN KEY(SCRNO) REFERENCES SCREEN(SCRNO)
);

CREATE TABLE PAY(
<<<<<<< HEAD
PAYNO NUMBER, --°áÁ¦ ¹øÈ£
PAYWAY VARCHAR2, --°áÁ¦¹æ½Ä
PRICE NUMBER, --°áÁ¦ °¡°Ý
=======
PAYNO NUMBER, --ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½È£
PAYWAY VARCHAR2, --ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
PRICE NUMBER, --ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
>>>>>>> d44d9151d7cd44fcf351008a550749065f5d2c5d
FOREIGN KEY(POINT) REFERENCES USER(POINT),
FOREIGN KEY(USERID) REFERENCES USER(USERID),
PRIMARY KEY(PAYNO)
);

CREATE TABLE GENRE(
GENRENO NUMBER,
GENRENAME VARCHAR2
);

CREATE TABLE USER(
<<<<<<< HEAD
USERID VARCHAR2,--¾ÆÀÌµð
USERNAME VARCHAR2,--ÀÌ¸§
USERPW VARCHAR2,--ºñ¹Ð¹øÈ£
USEREMAIL VARCHAR2,--ÀÌ¸ÞÀÏ
USERBITRH DATE,--»ý³â¿ùÀÏ
USERPHONE NUMBER, --ÀüÈ­¹øÈ£
POINT NUMBER, --Æ÷ÀÎÆ®
=======
USERID VARCHAR2,--ï¿½ï¿½ï¿½Ìµï¿½
USERNAME VARCHAR2,--ï¿½Ì¸ï¿½
USERPW VARCHAR2,--ï¿½ï¿½Ð¹ï¿½È£
USEREMAIL VARCHAR2,--ï¿½Ì¸ï¿½ï¿½ï¿½
USERBITRH DATE,--ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
USERPHONE NUMBER, --ï¿½ï¿½È­ï¿½ï¿½È£
POINT NUMBER, --ï¿½ï¿½ï¿½ï¿½Æ®
>>>>>>> d44d9151d7cd44fcf351008a550749065f5d2c5d
FOREIGN KEY(FAVORGENRE) REFERENCES GENRE(GENRONO),
FOREIGN KEY(TICKETNO) REFERENCES SEAT(TICKETNO)
);

CREATE TABLE POINT(

<<<<<<< HEAD
=======
CREATE TABLE MOVIE(
MVNO NUMBER , -- ¿µÈ­ ¹øÈ£
MVNAME VARCHAR2 NOT NULL, -- ¿µÈ­ ÀÌ¸§
MVDIRECTOR VARCHAR2 NOT NULL, --¿µÈ­ °¨µ¶
MVCLASS VARCHAR2 NOT NULL,--¿µÈ­µî±Þ
MVBOOKINGRATE NUMBER, --¿µÈ­ ¿¹¸Å·ü / °è»ê ÇÊ¿ä
MVBOOKRANK NUMBER, --¿µÈ­ ¿¹¸Å ¼øÀ§ / °è»ê ÇÊ¿ä
MVONSCREEN BOOLEAN NOT NULL,--¿µÈ­ »ó¿µ ¿©ºÎ
MVRUNTIME NUMBER, --¿µÈ­ ½Ã°£
FOREIGN KEY(GENRENO) REFERENCES GENRE(GENRONO),
PRIMARY KEY(MVNO)
);

CREATE TABLE SCREENWAY(
SCRNO NUMBER,
SCRWAY VARCHAR2
);

CREATE TABLE SCREEN (
SCRNO NUMBER, --»ó¿µ ¹øÈ£
ZONE VARCHAR2, --Áö¿ª
SCRDATE DATE, --»ó¿µ³¯Â¥
CINEMA VARCHAR2, --¿µÈ­°ü
THEATER VARCHAR2, --»ó¿µ°ü
FOREIGN KEY(SCRWAY) REFERENCES SCREENWAY(SCRNO),
PRIMARY KEY(SCRNO)
);

CREATE TABLE CINEMA (

);


CREATE TABLE THEATER (

SCRSTART NUMBER, --»ó¿µ½ÃÀÛ½Ã°£ 
SCREND NUMBER, --»ó¿µÁ¾·á½Ã°£

);

CREATE TABLE SEAT (
TICKETNO NUMBER, --Æ¼ÄÏ ÀÏ·Ã¹øÈ£
SEATCNT NUMBER, --ÁÂ¼® °³¼ö
KIND VARCHAR2, --°ü¶÷ÀÎ Á¾·ù
SEATNUM NUMBER, --ÁÂ¼® ¹øÈ£(ÁÂ¼® ¹èÄ¡ °í·Á X)
PRIMARY KEY(TICKETNO),
FOREIGN KEY(SCRNO) REFERENCES SCREEN(SCRNO)
);

CREATE TABLE PAY(
PAYNO NUMBER, --°áÁ¦ ¹øÈ£
PAYWAY VARCHAR2, --°áÁ¦¹æ½Ä
PRICE NUMBER, --°áÁ¦ °¡°Ý
FOREIGN KEY(POINT) REFERENCES USER(POINT),
FOREIGN KEY(USERID) REFERENCES USER(USERID),
PRIMARY KEY(PAYNO)
);

CREATE TABLE GENRE(
GENRENO NUMBER,
GENRENAME VARCHAR2
);

CREATE TABLE USER(
USERID VARCHAR2,--¾ÆÀÌµð
USERNAME VARCHAR2,--ÀÌ¸§
USERPW VARCHAR2,--ºñ¹Ð¹øÈ£
USEREMAIL VARCHAR2,--ÀÌ¸ÞÀÏ
USERBITRH DATE,--»ý³â¿ùÀÏ
USERPHONE NUMBER, --ÀüÈ­¹øÈ£
POINT NUMBER, --Æ÷ÀÎÆ®
FOREIGN KEY(FAVORGENRE) REFERENCES GENRE(GENRONO),
FOREIGN KEY(TICKETNO) REFERENCES SEAT(TICKETNO)
);

CREATE TABLE POINT(

>>>>>>> a5e53db03f5ed16c074539fddfd4b6a364787342
=======
>>>>>>> d44d9151d7cd44fcf351008a550749065f5d2c5d
);