CREATE TABLE MOVIE(
MVNO NUMBER , -- ��ȭ ��ȣ
MVNAME VARCHAR2 NOT NULL, -- ��ȭ �̸�
MVDIRECTOR VARCHAR2 NOT NULL, --��ȭ ����
MVCLASS VARCHAR2 NOT NULL,--��ȭ���
MVBOOKINGRATE NUMBER, --��ȭ ���ŷ� / ��� �ʿ�
MVBOOKRANK NUMBER, --��ȭ ���� ���� / ��� �ʿ�
MVONSCREEN BOOLEAN NOT NULL,--��ȭ �� ����
MVRUNTIME NUMBER, --��ȭ �ð�
FOREIGN KEY(GENRENO) REFERENCES GENRE(GENRONO), --NOT KEY?
PRIMARY KEY(MVNO)
);

CREATE TABLE SCREENWAY(
SCRWAYNO NUMBER,
SCRWAY VARCHAR2
PRIMARY KEY(SCRWAYNO)
);

CREATE TABLE MOVIE-SCREEN (
RELEASEDATE DATE, 
CLOSEDATE DATE, 
FOREIGN KEY(SCRNO) REFERENCES SCREEN(SCRNO),
FOREIGN KEY(THEATERNO) REFERENCES SCREEN(THEATERNO),
FOREIGN KEY(CINEMANO) REFERENCES SCREEN(CINEMANO),
FOREIGN KEY(MVNO) REFERENCES MOVIE(MVNO)
);

CREATE TABLE SCREEN (
SCRNO NUMBER, --�� ��ȣ
SCRDATE DATE, --�󿵳�¥
SCRSTART NUMBER,
SCREND NUMBER,
FOREIGN KEY(SCREENWATNO) REFERENCES SCREENWAY(SCREENWAYNO),--NOT KEY?
FOREIGN KEY(THEATERNO) REFERENCES SCREEN(THEATERNO),
FOREIGN KEY(CINEMANO) REFERENCES SCREEN(CINEMANO),
PRIMARY KEY(SCRNO)
);

CREATE TABLE CINEMA (
CINEMANO NUMBER,
CINEMANAME VARCHAR2,
ZONE VARCHAR2, --����
);


CREATE TABLE THEATER (
THEATERKIND VARCHAR2,
THEATERNO NUMBER,
PRIMARY KEY(THEATERNO),
FOREIGN KEY(CINEMANO) REFERENCES CINEMA(CINEMANO),
);

CREATE TABLE SEAT (
SEATNO NUMBER, --Ƽ�� �Ϸù�ȣ
SEATCNT NUMBER, --�¼� ����
KIND VARCHAR2, --������ ����
PRIMARY KEY(SEATNO),
FOREIGN KEY(SCRNO) REFERENCES SCREEN(SCRNO),
FOREIGN KEY(CINEMANO) REFERENCES CINEMA(CINEMANO),
FOREIGN KEY(THEATERNO) REFERENCES THEATER(THEATERNO),
FOREIGN KEY(USERID) REFERENCES USER(USERID),
FOREIGN KEY(PAYNO) REFERENCES PAY(PAYNO)
);

CREATE TABLE PAY(
PAYNO NUMBER, --���� ��ȣ
PAYWAY VARCHAR2, --�������
PRICE NUMBER, --���� ����
FOREIGN KEY(USERID) REFERENCES USER(USERID),
PRIMARY KEY(PAYNO)
);

CREATE TABLE GENRE(
GENRENO NUMBER,
GENRENAME VARCHAR2
);

CREATE TABLE USER(
USERID VARCHAR2,--���̵�
USERNAME VARCHAR2,--�̸�
USERPW VARCHAR2,--��й�ȣ
USEREMAIL VARCHAR2,--�̸���
USERBITRH DATE,--�������
USERPHONE NUMBER, --��ȭ��ȣ
POINT NUMBER, --����Ʈ
BONIN BOOLEAN,
FOREIGN KEY(FAVORGENRE) REFERENCES GENRE(GENRONO),--NOT KEY?
PRIMARY KEY(USERID)
);

CREATE TABLE POINTREC(
VOLUME NUMBER,
INOUT BOOLEAN,
UPDATEDATE DATE,
FOREIGN KEY(USERID) REFERENCES USER(USERID),
);

CREATE TABLE GOVERMENT(
CITIZENRESINO NUMBER,
CITIZENNAME VARCHAR2,
CITIZENPHONE NUMBER,
PRIMARY KEY(CITIZENRESINO)
);