/*
    # 2021년 기준 02년생까지 청불 영화가능
*/

-- 영화 도메인(영화 크롤링) 

-- 관리자 도메인
-- INSERT INTO MANAGER_INFO VALUES(비밀번호, 이름, 아이디);
INSERT INTO MANAGER_INFO VALUES("aaa1111!", "강진호", "bubble3jh456");
INSERT INTO MANAGER_INFO VALUES("bbb2222!", "양다은", "daaeun123");

-- 본인인증 도메인
-- INSERT INTO VERIFICATION VALUES(이름, 전화번호, 생년월일);
INSERT INTO VERIFICATION VALUES(이름, 01011112222, 001204);

-- 지역 도메인
-- INSERT INTO LOCAL VALUES(식별문자, 이름);
INSERT INTO LOCAL VALUES(LOACL01, "정문통학마을");
INSERT INTO LOCAL VALUES(LOACL02, "학식러버마을");
INSERT INTO LOCAL VALUES(LOACL03, "후문자취마을");
INSERT INTO LOCAL VALUES(LOACL04, "하늘연못마을");
INSERT INTO LOCAL VALUES(LOACL05, "쪽운동장마을");

-- 영화관 도메인
-- INSERT INTO CINEMA VALUES(식별문자, 이름, 지역_식별문자);
INSERT INTO CINEMA VALUES(CINEMA01, "전농관", LOACL01);
INSERT INTO CINEMA VALUES(CINEMA02, "자작마루", LOACL01);
INSERT INTO CINEMA VALUES(CINEMA03, "건공관", LOACL01);
INSERT INTO CINEMA VALUES(CINEMA04, "학관", LOACL02);
INSERT INTO CINEMA VALUES(CINEMA05, "21관", LOACL02);
INSERT INTO CINEMA VALUES(CINEMA06, "자과관", LOACL02);
INSERT INTO CINEMA VALUES(CINEMA07, "창공관", LOACL03);
INSERT INTO CINEMA VALUES(CINEMA08, "배봉관", LOACL03);
INSERT INTO CINEMA VALUES(CINEMA09, "정기관", LOACL04);
INSERT INTO CINEMA VALUES(CINEMA10, "인문학관", LOACL04);
INSERT INTO CINEMA VALUES(CINEMA11, "음악관", LOACL04);
INSERT INTO CINEMA VALUES(CINEMA12, "과기관", LOACL05);
INSERT INTO CINEMA VALUES(CINEMA13, "미래관", LOACL05);
INSERT INTO CINEMA VALUES(CINEMA14, "백기관", LOACL05);


-- 상영방식 도메인
-- INSERT INTO SCREENWAY VALUES(식별문자, 상영방식, 상영금액);
INSERT INTO SCREENWAY VALUES(SCRWAY01, "2D", 10000);
INSERT INTO SCREENWAY VALUES(SCRWAY02, "3D", 20000);
INSERT INTO SCREENWAY VALUES(SCRWAY03, "4DX", 30000);
INSERT INTO SCREENWAY VALUES(SCRWAY04, "SOUNDX", 30000);

-- 상영관 도메인
-- INSERT INTO THEATER VALUES(식별문자, 좌석수, 상영중여부, 영화관_식별문자, 상영방식_식별문자, 영화_식별문자);
INSERT INTO THEATER VALUES(THEATER01, 100, 0, CINEMA01, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER02, 80, 0, CINEMA01, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER03, 60, 0, CINEMA01, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER04, 40, 0, CINEMA01, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER05, 20, 0, CINEMA01, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER06, 100, 0, CINEMA02, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER07, 80, 0, CINEMA02, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER08, 60, 0, CINEMA02, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER09, 40, 0, CINEMA02, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER10, 20, 0, CINEMA02, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER11, 100, 0, CINEMA01, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER12, 80, 0, CINEMA03, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER13, 60, 0, CINEMA03, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER14, 40, 0, CINEMA03, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER15, 20, 0, CINEMA03, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER16, 100, 0, CINEMA04, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER17, 80, 0, CINEMA04, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER18, 60, 0, CINEMA04, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER19, 40, 0, CINEMA04, SCRWAY01, MV00001);
INSERT INTO THEATER VALUES(THEATER20, 20, 0, CINEMA04, SCRWAY01, MV00001);

-- 좌석 도메인
-- 관객방식 도메인




--영화를 등록한다.
INSERT INTO MOVIE VALUES(1, '겨울왕국2', 20200514, '봉준호', '청불', 120, '로맨틱코미디', '엘사가 안나를..?', 1, 100 );

--영화를 제거한다.
DELETE FROM MOVIE WHERE MVNO=1;

--영화 상영 일정을 등록한다.
INSERT INTO SCREEN VALUES(1, 20200514, 1830, 15)

--영화 상영 일정을 제거한다.
DELETE FROM SCREEN WHERE SCRNO=1;

--고객 정보를 입력한다.(본인인증 포함)
INSERT INTO USER VALUES(DEJH, TRUE)
INSERT INTO MEMBER VALUES( ... )

--회원 정보를 수정한다.
UPDATE MEMBER SET MEMPHONE=01012345678;

--회원탈퇴한다.
DELETE FROM USER WHERE USERID=bubble3jh
DELETE FROM MEMBER WHERE USERID=bubble3jh

--고객이 키워드를 가지고 영화를 검색한다.
SELECT MVNAME FROM MOVIE WHERE MVDIRECTOR='봉준호';

--영화관을 선택해 상영중인 영화를 검색한다. (!)
SELECT MVNAME FROM MOVIE WHERE EXISTS (SELECT 1 FROM THEATER WHERE THEATER.CINEMANO = '10' AND ONSCREEN = TRUE AND THEATER.MVNO = MOVIE.MVNO);

--상영중인 영화를 예매율 순으로 정렬한다. (!)
SELECT MVNAME FROM MOVIE WHERE EXISTS (SELECT 1 FROM THEATER WHERE ONSCREEN = TRUE AND THEATER.MVNO = MOVIE.MVNO) ORDER BY MVBOOKINGRATE;

--결제자가 시청 가능한 영화인지 확인한다.
SELECT MVCLASS ,CASE WHEN MVCLASS='청불' 

--영화관, 상영관, 좌석을 선택한다.(예매율 정보 UPDATE)
INSERT INTO BOOKING_INFO (BOOKNO, BOOKINGDATE) VALUES(1, GETDATE())
INSERT INTO PAY_INFO (PAYNO, PRICE) VALUES(1, 10000) -- 예매율 정보를 UPDATE 하기 위해서 MV에 타고 가야하는데 예매정보에 영화/ 상영 관련 항목이 없음..?

--포인트 결제자 사용자 회원 VIEW
CREATE OR REPLACE VIEW PAYPOINT AS
SELECT PAY_INFO.PRICE
SELECT POINT.SCORE
FROM PAY_INFO INNER JOIN PAY_INFO ON PAY_INFO.USERID = POINT.USERID
WHERE PAY_INFO.USERID = POINT.USERID;

--포인트로 할인을 받는다. (1번 결제에서 5000원 할인)
UPDATE PAY_INFO SET PRICE= (SELECT PRICE FROM PAY_INFO WHERE PAYNO='1')-5000
UPDATE POINT SET SCORE= (SELECT SCORE FROM POINT WHERE USERID='bubble3jh')-5000

--결제 후 포인트를 적립한다. (1번 결제 최종 금액의 10% 적립)
UPDATE POINT SET SCORE= (SELECT SCORE FROM POINT WHERE USERID='bubble3jh')+(SELECT PRICE FROM PAY_INFO WHERE PAYNO='1')*0.1

--결제를 완료한다.
UPDATE PAY_INFO SET PAYDATE = GETDATE(), PAYWAY = '우리은행';

--예매를 취소한다. (예매율 정보 UPDATE)
DELETE * FROM BOOKING_INFO WHERE BOOKNO = '1';

--결제 완료된 예매정보를 확인한다.
SELECT * FROM BOOKING_INFO WHERE BOOKNO = '1';
